name: grocify
description: "A new Flutter project."


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.4.3



#---------------------PACKAGES---------------------#
dependencies:
  flutter:
    sdk: flutter


  #UTILITY PACKAGES
  http: ^1.1.0
  intl: ^0.20.1
  logger: ^2.0.1
  lottie: ^3.3.1
  shimmer: ^3.0.0
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  url_launcher: ^6.1.12
  connectivity_plus: ^6.1.3
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3




  #ICONS
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8


  #STATE MANAGEMENT
  get: ^4.6.5
  get_storage: ^2.1.1

  #PROGECT SPECIFIC
  readmore: ^2.2.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1

  # Firebase
  mime: ^1.0.4
  supabase_flutter: ^1.10.12

  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  google_sign_in: ^6.3.0
  firebase_storage: ^12.4.5
  cached_network_image: ^3.4.1
  path: ^1.9.0
  fake_cloud_firestore: ^3.0.2


  #------------/. PACKAGES END ---------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  mockito: ^5.4.5
  build_runner: ^2.4.6
  test: ^1.24.0
  firebase_auth_mocks: ^0.14.1
  google_sign_in_mocks: ^0.3.0




  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true


  #------------LOCAL ASSETS---------------#
  assets:
    - assets/logos/
    - assets/fonts/
    - assets/images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/user/
    - assets/icons/brands/
    - assets/images/reviews/
    - assets/icons/payment_methods/






  #----------LOCAL FONTS---------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800